/**
 * @file mc_registry_names.h
 * @brief 同步注册表的条目名列表（数据由客户端 known pack 提供）。
 * @note 由 scripts/gen_registry_names.py 从客户端 jar 生成。
 */
#ifndef _MC_REGISTRY_NAMES_H_
#define _MC_REGISTRY_NAMES_H_

#include <stdint.h>

static const char *const mc_reg_0[] = {
  "minecraft:plains",
  "minecraft:badlands",
  "minecraft:bamboo_jungle",
  "minecraft:basalt_deltas",
  "minecraft:beach",
  "minecraft:birch_forest",
  "minecraft:cherry_grove",
  "minecraft:cold_ocean",
  "minecraft:crimson_forest",
  "minecraft:dappled_forest",
  "minecraft:dark_forest",
  "minecraft:deep_cold_ocean",
  "minecraft:deep_dark",
  "minecraft:deep_frozen_ocean",
  "minecraft:deep_lukewarm_ocean",
  "minecraft:deep_ocean",
  "minecraft:desert",
  "minecraft:dripstone_caves",
  "minecraft:end_barrens",
  "minecraft:end_highlands",
  "minecraft:end_midlands",
  "minecraft:eroded_badlands",
  "minecraft:flower_forest",
  "minecraft:forest",
  "minecraft:frozen_ocean",
  "minecraft:frozen_peaks",
  "minecraft:frozen_river",
  "minecraft:grove",
  "minecraft:ice_spikes",
  "minecraft:jagged_peaks",
  "minecraft:jungle",
  "minecraft:lukewarm_ocean",
  "minecraft:lush_caves",
  "minecraft:mangrove_swamp",
  "minecraft:meadow",
  "minecraft:mushroom_fields",
  "minecraft:nether_wastes",
  "minecraft:ocean",
  "minecraft:old_growth_birch_forest",
  "minecraft:old_growth_pine_taiga",
  "minecraft:old_growth_spruce_taiga",
  "minecraft:pale_garden",
  "minecraft:river",
  "minecraft:savanna",
  "minecraft:savanna_plateau",
  "minecraft:small_end_islands",
  "minecraft:snowy_beach",
  "minecraft:snowy_plains",
  "minecraft:snowy_slopes",
  "minecraft:snowy_taiga",
  "minecraft:soul_sand_valley",
  "minecraft:sparse_jungle",
  "minecraft:stony_peaks",
  "minecraft:stony_shore",
  "minecraft:sulfur_caves",
  "minecraft:sunflower_plains",
  "minecraft:swamp",
  "minecraft:taiga",
  "minecraft:the_end",
  "minecraft:the_void",
  "minecraft:warm_ocean",
  "minecraft:warped_forest",
  "minecraft:windswept_forest",
  "minecraft:windswept_gravelly_hills",
  "minecraft:windswept_hills",
  "minecraft:windswept_savanna",
  "minecraft:wooded_badlands",
};
static const char *const mc_reg_1[] = {
  "minecraft:overworld",
  "minecraft:overworld_caves",
  "minecraft:the_end",
  "minecraft:the_nether",
};
static const char *const mc_reg_2[] = {
  "minecraft:chat",
  "minecraft:emote_command",
  "minecraft:msg_command_incoming",
  "minecraft:msg_command_outgoing",
  "minecraft:say_command",
  "minecraft:team_msg_command_incoming",
  "minecraft:team_msg_command_outgoing",
};
static const char *const mc_reg_3[] = {
  "minecraft:bolt",
  "minecraft:coast",
  "minecraft:dune",
  "minecraft:eye",
  "minecraft:flow",
  "minecraft:host",
  "minecraft:raiser",
  "minecraft:rib",
  "minecraft:sentry",
  "minecraft:shaper",
  "minecraft:silence",
  "minecraft:snout",
  "minecraft:spire",
  "minecraft:tide",
  "minecraft:vex",
  "minecraft:ward",
  "minecraft:wayfinder",
  "minecraft:wild",
};
static const char *const mc_reg_4[] = {
  "minecraft:amethyst",
  "minecraft:copper",
  "minecraft:diamond",
  "minecraft:emerald",
  "minecraft:gold",
  "minecraft:iron",
  "minecraft:lapis",
  "minecraft:netherite",
  "minecraft:quartz",
  "minecraft:redstone",
  "minecraft:resin",
};
static const char *const mc_reg_5[] = {
  "minecraft:ashen",
  "minecraft:black",
  "minecraft:chestnut",
  "minecraft:pale",
  "minecraft:rusty",
  "minecraft:snowy",
  "minecraft:spotted",
  "minecraft:striped",
  "minecraft:woods",
};
static const char *const mc_reg_6[] = {
  "minecraft:angry",
  "minecraft:big",
  "minecraft:classic",
  "minecraft:cute",
  "minecraft:grumpy",
  "minecraft:puglin",
  "minecraft:sad",
};
static const char *const mc_reg_7[] = {
  "minecraft:cold",
  "minecraft:temperate",
  "minecraft:warm",
};
static const char *const mc_reg_8[] = {
  "minecraft:big",
  "minecraft:classic",
  "minecraft:mini",
};
static const char *const mc_reg_9[] = {
  "minecraft:cold",
  "minecraft:temperate",
  "minecraft:warm",
};
static const char *const mc_reg_10[] = {
  "minecraft:all_black",
  "minecraft:black",
  "minecraft:british_shorthair",
  "minecraft:calico",
  "minecraft:jellie",
  "minecraft:persian",
  "minecraft:ragdoll",
  "minecraft:red",
  "minecraft:siamese",
  "minecraft:tabby",
  "minecraft:white",
};
static const char *const mc_reg_11[] = {
  "minecraft:classic",
  "minecraft:royal",
};
static const char *const mc_reg_12[] = {
  "minecraft:cold",
  "minecraft:temperate",
  "minecraft:warm",
};
static const char *const mc_reg_13[] = {
  "minecraft:classic",
  "minecraft:moody",
};
static const char *const mc_reg_14[] = {
  "minecraft:cold",
  "minecraft:temperate",
  "minecraft:warm",
};
static const char *const mc_reg_15[] = {
  "minecraft:classic",
  "minecraft:picky",
};
static const char *const mc_reg_16[] = {
  "minecraft:temperate",
  "minecraft:warm",
};
static const char *const mc_reg_17[] = {
  "minecraft:alban",
  "minecraft:aztec",
  "minecraft:aztec2",
  "minecraft:backyard",
  "minecraft:baroque",
  "minecraft:bomb",
  "minecraft:bouquet",
  "minecraft:burning_skull",
  "minecraft:bust",
  "minecraft:cavebird",
  "minecraft:changing",
  "minecraft:cotan",
  "minecraft:courbet",
  "minecraft:creebet",
  "minecraft:dennis",
  "minecraft:donkey_kong",
  "minecraft:earth",
  "minecraft:endboss",
  "minecraft:fern",
  "minecraft:fighters",
  "minecraft:finding",
  "minecraft:fire",
  "minecraft:graham",
  "minecraft:humble",
  "minecraft:kebab",
  "minecraft:lowmist",
  "minecraft:match",
  "minecraft:meditative",
  "minecraft:orb",
  "minecraft:owlemons",
  "minecraft:passage",
  "minecraft:pigscene",
  "minecraft:plant",
  "minecraft:pointer",
  "minecraft:pond",
  "minecraft:pool",
  "minecraft:prairie_ride",
  "minecraft:sea",
  "minecraft:skeleton",
  "minecraft:skull_and_roses",
  "minecraft:stage",
  "minecraft:sunflowers",
  "minecraft:sunset",
  "minecraft:tides",
  "minecraft:unpacked",
  "minecraft:void",
  "minecraft:wanderer",
  "minecraft:wasteland",
  "minecraft:water",
  "minecraft:wind",
  "minecraft:wither",
};
static const char *const mc_reg_18[] = {
  "minecraft:bouncy",
  "minecraft:explosive",
  "minecraft:fast_flat",
  "minecraft:fast_sliding",
  "minecraft:high_resistance",
  "minecraft:hot",
  "minecraft:light",
  "minecraft:regular",
  "minecraft:slow_bouncy",
  "minecraft:slow_flat",
  "minecraft:slow_sliding",
  "minecraft:sticky",
};
static const char *const mc_reg_19[] = {
  "minecraft:arrow",
  "minecraft:bad_respawn_point",
  "minecraft:cactus",
  "minecraft:campfire",
  "minecraft:cramming",
  "minecraft:dragon_breath",
  "minecraft:drown",
  "minecraft:dry_out",
  "minecraft:ender_pearl",
  "minecraft:explosion",
  "minecraft:fall",
  "minecraft:falling_anvil",
  "minecraft:falling_block",
  "minecraft:falling_stalactite",
  "minecraft:fireball",
  "minecraft:fireworks",
  "minecraft:fly_into_wall",
  "minecraft:freeze",
  "minecraft:generic",
  "minecraft:generic_kill",
  "minecraft:hot_floor",
  "minecraft:in_fire",
  "minecraft:in_wall",
  "minecraft:indirect_magic",
  "minecraft:lava",
  "minecraft:lightning_bolt",
  "minecraft:mace_smash",
  "minecraft:magic",
  "minecraft:mob_attack",
  "minecraft:mob_attack_no_aggro",
  "minecraft:mob_projectile",
  "minecraft:on_fire",
  "minecraft:out_of_world",
  "minecraft:outside_border",
  "minecraft:player_attack",
  "minecraft:player_explosion",
  "minecraft:sonic_boom",
  "minecraft:spear",
  "minecraft:spit",
  "minecraft:stalagmite",
  "minecraft:starve",
  "minecraft:sting",
  "minecraft:sulfur_cube_hot",
  "minecraft:sweet_berry_bush",
  "minecraft:thorns",
  "minecraft:thrown",
  "minecraft:trident",
  "minecraft:unattributed_fireball",
  "minecraft:wind_charge",
  "minecraft:wither",
  "minecraft:wither_skull",
};
static const char *const mc_reg_20[] = {
  "minecraft:base",
  "minecraft:border",
  "minecraft:bricks",
  "minecraft:circle",
  "minecraft:creeper",
  "minecraft:cross",
  "minecraft:curly_border",
  "minecraft:diagonal_left",
  "minecraft:diagonal_right",
  "minecraft:diagonal_up_left",
  "minecraft:diagonal_up_right",
  "minecraft:flow",
  "minecraft:flower",
  "minecraft:globe",
  "minecraft:gradient",
  "minecraft:gradient_up",
  "minecraft:guster",
  "minecraft:half_horizontal",
  "minecraft:half_horizontal_bottom",
  "minecraft:half_vertical",
  "minecraft:half_vertical_right",
  "minecraft:mojang",
  "minecraft:piglin",
  "minecraft:rhombus",
  "minecraft:skull",
  "minecraft:small_stripes",
  "minecraft:square_bottom_left",
  "minecraft:square_bottom_right",
  "minecraft:square_top_left",
  "minecraft:square_top_right",
  "minecraft:straight_cross",
  "minecraft:stripe_bottom",
  "minecraft:stripe_center",
  "minecraft:stripe_downleft",
  "minecraft:stripe_downright",
  "minecraft:stripe_left",
  "minecraft:stripe_middle",
  "minecraft:stripe_right",
  "minecraft:stripe_top",
  "minecraft:triangle_bottom",
  "minecraft:triangle_top",
  "minecraft:triangles_bottom",
  "minecraft:triangles_top",
};
static const char *const mc_reg_21[] = {
  "minecraft:aqua_affinity",
  "minecraft:bane_of_arthropods",
  "minecraft:binding_curse",
  "minecraft:blast_protection",
  "minecraft:breach",
  "minecraft:channeling",
  "minecraft:density",
  "minecraft:depth_strider",
  "minecraft:efficiency",
  "minecraft:feather_falling",
  "minecraft:fire_aspect",
  "minecraft:fire_protection",
  "minecraft:flame",
  "minecraft:fortune",
  "minecraft:frost_walker",
  "minecraft:impaling",
  "minecraft:infinity",
  "minecraft:knockback",
  "minecraft:looting",
  "minecraft:loyalty",
  "minecraft:luck_of_the_sea",
  "minecraft:lunge",
  "minecraft:lure",
  "minecraft:mending",
  "minecraft:multishot",
  "minecraft:piercing",
  "minecraft:power",
  "minecraft:projectile_protection",
  "minecraft:protection",
  "minecraft:punch",
  "minecraft:quick_charge",
  "minecraft:respiration",
  "minecraft:riptide",
  "minecraft:sharpness",
  "minecraft:silk_touch",
  "minecraft:smite",
  "minecraft:soul_speed",
  "minecraft:sweeping_edge",
  "minecraft:swift_sneak",
  "minecraft:thorns",
  "minecraft:unbreaking",
  "minecraft:vanishing_curse",
  "minecraft:wind_burst",
};
static const char *const mc_reg_22[] = {
  "minecraft:11",
  "minecraft:13",
  "minecraft:5",
  "minecraft:blocks",
  "minecraft:bounce",
  "minecraft:cat",
  "minecraft:chirp",
  "minecraft:creator",
  "minecraft:creator_music_box",
  "minecraft:far",
  "minecraft:lava_chicken",
  "minecraft:mall",
  "minecraft:mellohi",
  "minecraft:otherside",
  "minecraft:pigstep",
  "minecraft:precipice",
  "minecraft:relic",
  "minecraft:stal",
  "minecraft:strad",
  "minecraft:tears",
  "minecraft:wait",
  "minecraft:ward",
};
static const char *const mc_reg_23[] = {
  "minecraft:admire_goat_horn",
  "minecraft:call_goat_horn",
  "minecraft:dream_goat_horn",
  "minecraft:feel_goat_horn",
  "minecraft:ponder_goat_horn",
  "minecraft:seek_goat_horn",
  "minecraft:sing_goat_horn",
  "minecraft:yearn_goat_horn",
};
static const char *const mc_reg_24[] = {
  "minecraft:default",
};
static const char *const mc_reg_25[] = {
  "minecraft:always_pass",
};
static const char *const mc_reg_26[] = {
  "minecraft:custom_options",
  "minecraft:quick_actions",
  "minecraft:server_links",
};
static const char *const mc_reg_27[] = {
  "minecraft:overworld",
  "minecraft:the_end",
};
static const char *const mc_reg_28[] = {
  "minecraft:day",
  "minecraft:early_game",
  "minecraft:moon",
  "minecraft:villager_schedule",
};
static const char *const mc_reg_29[] = {
  "minecraft:angler",
  "minecraft:archer",
  "minecraft:arms_up",
  "minecraft:blade",
  "minecraft:brewer",
  "minecraft:burn",
  "minecraft:danger",
  "minecraft:explorer",
  "minecraft:flow",
  "minecraft:friend",
  "minecraft:guster",
  "minecraft:heart",
  "minecraft:heartbreak",
  "minecraft:howl",
  "minecraft:miner",
  "minecraft:mourner",
  "minecraft:plenty",
  "minecraft:prize",
  "minecraft:scrape",
  "minecraft:sheaf",
  "minecraft:shelter",
  "minecraft:skull",
  "minecraft:snort",
};
static const char *const mc_reg_30[] = {
  "minecraft:axe",
  "minecraft:hoe",
  "minecraft:shovel",
};
static const char *const mc_reg_31[] = {
  (const char *)0,
};

typedef struct {
  const char *registry;
  uint16_t count;
  const char *const *names;
} mc_registry_desc_t;

static const mc_registry_desc_t mc_registries[] = {
  {"minecraft:worldgen/biome", 67U, mc_reg_0},
  {"minecraft:dimension_type", 4U, mc_reg_1},
  {"minecraft:chat_type", 7U, mc_reg_2},
  {"minecraft:trim_pattern", 18U, mc_reg_3},
  {"minecraft:trim_material", 11U, mc_reg_4},
  {"minecraft:wolf_variant", 9U, mc_reg_5},
  {"minecraft:wolf_sound_variant", 7U, mc_reg_6},
  {"minecraft:pig_variant", 3U, mc_reg_7},
  {"minecraft:pig_sound_variant", 3U, mc_reg_8},
  {"minecraft:frog_variant", 3U, mc_reg_9},
  {"minecraft:cat_variant", 11U, mc_reg_10},
  {"minecraft:cat_sound_variant", 2U, mc_reg_11},
  {"minecraft:cow_variant", 3U, mc_reg_12},
  {"minecraft:cow_sound_variant", 2U, mc_reg_13},
  {"minecraft:chicken_variant", 3U, mc_reg_14},
  {"minecraft:chicken_sound_variant", 2U, mc_reg_15},
  {"minecraft:zombie_nautilus_variant", 2U, mc_reg_16},
  {"minecraft:painting_variant", 51U, mc_reg_17},
  {"minecraft:sulfur_cube_archetype", 12U, mc_reg_18},
  {"minecraft:damage_type", 51U, mc_reg_19},
  {"minecraft:banner_pattern", 43U, mc_reg_20},
  {"minecraft:enchantment", 43U, mc_reg_21},
  {"minecraft:jukebox_song", 22U, mc_reg_22},
  {"minecraft:instrument", 8U, mc_reg_23},
  {"minecraft:test_environment", 1U, mc_reg_24},
  {"minecraft:test_instance", 1U, mc_reg_25},
  {"minecraft:dialog", 3U, mc_reg_26},
  {"minecraft:world_clock", 2U, mc_reg_27},
  {"minecraft:timeline", 4U, mc_reg_28},
  {"minecraft:decorated_pot_pattern", 23U, mc_reg_29},
  {"minecraft:block_transformer", 3U, mc_reg_30},
  {"minecraft:block_state_provider", 0U, mc_reg_31},
};

#define MC_REGISTRY_COUNT 32U

#endif /* _MC_REGISTRY_NAMES_H_ */
